In [13]:
import numpy as np
import random

In [2]:
np.array([3.1, 4, 5, 6])

array([3.1, 4. , 5. , 6. ])

In [3]:
np.array([1, 2, 3], dtype='float32')

array([1., 2., 3.], dtype=float32)

In [4]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.zeros((3, 5), dtype=float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones((3, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [8]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
np.linspace(0, 1, 7)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.seed(3)

In [12]:
x1 = np.random.randint(10, size=6) # Dimension table 1
print("dimensions number of x1:", x1.ndim)
print("shape of x1:", x1.shape)
print("size of x1:", x1.size)
print("type of x1:", x1.dtype)

dimensions number of x1: 1
shape of x1: (6,)
size of x1: 6
type of x1: int64


In [16]:
n=1000000
x = [random.random() for _ in range(n)]
y = [random.random() for _ in range(n)]


In [17]:
z = [x[i] + y[i] for i in range(n)]

In [20]:
%timeit 
[x[i] + y[i] for i in range(n)]

[0.3769507070943946,
 1.687892048713831,
 1.5006590512328026,
 0.6524808669586303,
 0.6734419098972007,
 0.25487643981396724,
 0.6446492885015408,
 1.1023803681449058,
 1.62806258960961,
 0.9928130318201276,
 1.1160007382719133,
 0.726946408091358,
 1.3790038083116085,
 1.4037865775961027,
 0.9093316200250726,
 0.593555834305092,
 1.1437308397352801,
 1.2544458650794987,
 0.6905271972992784,
 0.43997426478254775,
 0.7501619004693789,
 0.8355889161283027,
 1.3445138726287464,
 0.6947407464942285,
 0.6388856705298673,
 1.4976692146948518,
 1.1469717875451382,
 1.0702352434939688,
 0.9982488448562189,
 0.629028648954598,
 0.6675453908604974,
 0.16064219540083446,
 0.5351806607380789,
 0.9988384638926614,
 0.5691011978434791,
 1.160271227285261,
 0.9295264240685108,
 0.4524269231163749,
 0.658183151638891,
 0.6789977835760065,
 1.5667935655456398,
 0.9313968670967511,
 1.134307118068142,
 1.5313645751843419,
 1.146919249129828,
 0.3811461776751477,
 1.6684551695088345,
 0.6576445262646445,